{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
rules:
  {{- range .Values.rbac.rules }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 4 }}
    resources: {{ .resources | toYaml | nindent 4 }}
    verbs: {{ .verbs | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
