{{- if .Values.cm.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: {{ .Values.cm.settings | quote }}
  custom.css: {{ .Values.cm.customCSS | quote }}
  custom.js: {{ .Values.cm.customJS | quote }}
  bookmarks.yaml: {{ .Values.cm.bookmarks | quote }}
  services.yaml: {{ .Values.cm.services | quote }}
  widgets.yaml: {{ .Values.cm.widgets | quote }}
  docker.yaml: {{ .Values.cm.docker | quote }}
{{- end }}
